const {test}=require('node:test'),assert=require('node:assert/strict');
const load=()=>import('../online/presentation.mjs');
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const game=(id,status,player,updated='2026-10-03T10:00:00Z')=>({id,status,players:[A,B],names:['Rowan','Mara'],state:{player},updated_at:updated});
test('game list prioritizes actionable turns and keeps completed games separate',async()=>{const {visibleGames}=await load();const waiting=game('waiting','active',2,'2026-10-03T12:00:00Z'),mine=game('mine','active',1),finished={...game('done','completed',2),result:'1'},cancelled=game('cancel','cancelled',1);const list=[waiting,finished,mine,cancelled];assert.deepEqual(visibleGames(list,A).map(g=>g.id),['mine','waiting']);assert.deepEqual(new Set(visibleGames(list,A,'finished').map(g=>g.id)),new Set(['done','cancel']));assert.equal(list[0],waiting,'render ordering must not mutate API state');});
test('player-relative names and outcomes work from either seat',async()=>{const {opponentName,gameStatus}=await load(),g=game('g','active',2);assert.equal(opponentName(g,A),'Mara');assert.equal(opponentName(g,B),'Rowan');assert.equal(gameStatus(g,A),'Their turn');assert.equal(gameStatus(g,B),'Your turn');g.status='completed';g.result='2';assert.equal(gameStatus(g,A),'They won');assert.equal(gameStatus(g,B),'You won');g.result='draw';assert.equal(gameStatus(g,A),'A draw');});
test('invitation entry accepts a code or share URL and rejects malformed input',async()=>{const {invitationToken}=await load();assert.equal(invitationToken(' '+A+' '),A);assert.equal(invitationToken('https://example.com/online/?invite='+A),A);for(const value of ['','javascript:alert(1)','https://example.com/','not-a-code','https://example.com/?invite=garbage'])assert.equal(invitationToken(value),null);});
test('time labels handle recent, future, and missing dates',async()=>{const {timeAgo}=await load(),now=Date.parse('2026-10-03T12:00:00Z');assert.equal(timeAgo('2026-10-03T12:01:00Z',now),'Just now');assert.equal(timeAgo('2026-10-03T11:30:00Z',now),'30m ago');assert.equal(timeAgo('2026-10-02T11:30:00Z',now),'Yesterday');assert.equal(timeAgo('invalid',now),'');});
test('actionable error copy preserves dictionary feedback and hides implementation details',async()=>{const {friendlyError}=await load();assert.equal(friendlyError({code:'stale',message:'database revision failed'}),'A new turn came in. Your board has been updated.');assert.equal(friendlyError({name:'TypeError',message:'fetch failed'}),'Could not connect. Please try again.');assert.equal(friendlyError({code:'illegal_move',message:'That word is not in the dictionary.'}),'That word is not in the dictionary.');});
