const assert=require('node:assert/strict');
const E=require('./engine.js'), C={...require('./config.js'),endCondition:'turns'};
const stable={...C,refreshUsedLetters:false};
const fixture=word=>({tiles:[...word].map((letter,q)=>({id:String(q),q,r:0,letter,owner:q?0:1,castle:false})),player:1,turns:[0,0],wordPoints:[0,0],log:[],over:false});
const ids=state=>state.tiles.map(t=>t.id);
for(const [word,points] of [['CAT',4],['HOUNDS',14],['PIEHOLE',19],['JAZZ',14]]) {
  const state=fixture(word), before=JSON.stringify(state);
  const preview=E.scoreMove(state,ids(state),C);
  assert.equal(preview.wordPoints,points,word);
  const result=E.submit(state,ids(state),C);
  assert.deepEqual(result.state.log[0].scoring,preview,'Preview must exactly match awarded score');
  assert.equal(result.state.wordPoints[0],points);
  assert.equal(E.scores(result.state,C)[0],1+preview.totalGain);
  assert.equal(JSON.stringify(state),before,'Scoring and submission must not mutate original state');
}
assert.deepEqual([3,4,5,6,7,8,9,10].map(n=>E.lengthBonus(n,C)),[0,1,3,6,10,15,21,27]);
assert.equal(E.scoreMove(fixture(''),[],C).wordPoints,0);
for(const group of C.wordScoring.letterGroups)for(const letter of group.letters)assert.equal(E.letterValue(letter,C),group.points);
assert.equal(E.letterValue('?',C),0);
const joker=fixture('?AT');
assert.equal(E.submit(joker,ids(joker),C).error,'Choose one letter from A–Z for each joker.');
for(const chosen of ['C','Z'])assert.equal(E.submit(joker,ids(joker),C,null,{'0':chosen}).state.wordPoints[0],2);
const longJoker=fixture('???????');
const chosen=Object.fromEntries(ids(longJoker).map(id=>[id,'Z']));
assert.equal(E.submit(longJoker,ids(longJoker),C,null,chosen).state.wordPoints[0],10,'Wildcards count toward length only');
const owned=fixture('CAT');owned.tiles.forEach(t=>t.owner=1);
const ownResult=E.submit(owned,ids(owned),stable);
assert.deepEqual(ownResult.state.log[0].scoring,{letters:4,lengthBonus:0,wordPoints:4,territoryGain:0,enemyLoss:0,totalGain:4});
const battle=fixture('CATS');battle.tiles[1].castle=true;battle.tiles[2].owner=2;battle.tiles[3].owner=2;
const first=E.submit(battle,['0','1','2'],stable).state;
assert.deepEqual(first.log[0].scoring,{letters:4,lengthBonus:0,wordPoints:4,territoryGain:4,enemyLoss:1,totalGain:8});
assert.deepEqual(E.scoreBreakdown(first,C),[{words:4,territory:5,total:9},{words:0,territory:1,total:1}]);
const second=E.submit(first,['3','2','1'],stable).state;
assert.deepEqual(second.wordPoints,[4,3],'Opponent capture must not remove banked word points');
assert.equal(second.log[0].scoring.enemyLoss,4,'Enemy castle is worth three, not one');
assert.deepEqual(E.scores(second,C),[5,8]);
const third=E.submit(second,['0','1','2'],stable).state;
assert.deepEqual(third.wordPoints,[8,3],'Recapture banks only the new word, not extra capture points');
assert.deepEqual(E.scores(third,C),[13,4]);
const banked=JSON.stringify(third.wordPoints);
const refreshed=E.refreshTurn(third,C).state;
assert.equal(JSON.stringify(refreshed.wordPoints),banked);
assert.deepEqual(E.scores(refreshed,C),E.scores(third,C),'Refresh must not award income or change scores');
assert.ok(E.submit(third,['0','1'],C).error);
assert.equal(JSON.stringify(third.wordPoints),banked,'Rejected move cannot bank points');
const finish={...second,player:2,turns:[12,11],wordPoints:[100,0]};
const finished=E.submit(finish,['3','2','1'],stable).state;
assert.equal(finished.over,true);
assert.ok(E.scoreBreakdown(finished,C)[0].territory<E.scoreBreakdown(finished,C)[1].territory);
assert.ok(E.scores(finished,C)[0]>E.scores(finished,C)[1],'Total score, not territory, determines winner');
const tied={...second,wordPoints:[4,0]};
assert.deepEqual(E.scores(tied,C),[5,5]);
assert.deepEqual(E.newGame(C).wordPoints,[0,0],'New game resets bank');
const custom={...C,wordScoring:{...C.wordScoring,jokerPoints:2,lengthBonuses:[0,0,0,5],extraLetterBonus:10}};
assert.equal(E.scoreMove(joker,ids(joker),custom).wordPoints,9);
assert.equal(E.lengthBonus(4,custom),15);
console.log('Passed: scoring examples, length thresholds, jokers, preview agreement, no-capture moves, castle steals/recaptures, permanent points, refresh/invalid moves, totals, ties and reset.');
